export interface TerritoryFlag {
  readonly name: string;
  readonly code: string;
  readonly flagSrc: string;
}

// Territory/dependency reference set based on ISO 3166-1 non-country and special-area
// codes, with the Caribbean Netherlands and Saint Helena group split into their
// locally flagged components where the flag source provides distinct artwork.
export const territoryFlags: readonly TerritoryFlag[] = [
  { name: "American Samoa", code: "AS", flagSrc: "assets/flags/territories/as.svg" },
  { name: "Anguilla", code: "AI", flagSrc: "assets/flags/territories/ai.svg" },
  { name: "Antarctica", code: "AQ", flagSrc: "assets/flags/territories/aq.svg" },
  { name: "Ascension Island", code: "AC", flagSrc: "assets/flags/territories/ac.svg" },
  { name: "Aruba", code: "AW", flagSrc: "assets/flags/territories/aw.svg" },
  { name: "Åland Islands", code: "AX", flagSrc: "assets/flags/territories/ax.svg" },
  { name: "Bermuda", code: "BM", flagSrc: "assets/flags/territories/bm.svg" },
  { name: "Bonaire", code: "BQ-BO", flagSrc: "assets/flags/territories/bq-bo.svg" },
  { name: "Bouvet Island", code: "BV", flagSrc: "assets/flags/territories/bv.svg" },
  { name: "British Indian Ocean Territory", code: "IO", flagSrc: "assets/flags/territories/io.svg" },
  { name: "British Virgin Islands", code: "VG", flagSrc: "assets/flags/territories/vg.svg" },
  { name: "Cayman Islands", code: "KY", flagSrc: "assets/flags/territories/ky.svg" },
  { name: "Christmas Island", code: "CX", flagSrc: "assets/flags/territories/cx.svg" },
  { name: "Cocos (Keeling) Islands", code: "CC", flagSrc: "assets/flags/territories/cc.svg" },
  { name: "Cook Islands", code: "CK", flagSrc: "assets/flags/territories/ck.svg" },
  { name: "Curaçao", code: "CW", flagSrc: "assets/flags/territories/cw.svg" },
  { name: "Falkland Islands", code: "FK", flagSrc: "assets/flags/territories/fk.svg" },
  { name: "Faroe Islands", code: "FO", flagSrc: "assets/flags/territories/fo.svg" },
  { name: "French Guiana", code: "GF", flagSrc: "assets/flags/territories/gf.svg" },
  { name: "French Polynesia", code: "PF", flagSrc: "assets/flags/territories/pf.svg" },
  { name: "French Southern Territories", code: "TF", flagSrc: "assets/flags/territories/tf.svg" },
  { name: "Gibraltar", code: "GI", flagSrc: "assets/flags/territories/gi.svg" },
  { name: "Greenland", code: "GL", flagSrc: "assets/flags/territories/gl.svg" },
  { name: "Guadeloupe", code: "GP", flagSrc: "assets/flags/territories/gp.svg" },
  { name: "Guam", code: "GU", flagSrc: "assets/flags/territories/gu.svg" },
  { name: "Guernsey", code: "GG", flagSrc: "assets/flags/territories/gg.svg" },
  { name: "Heard Island and McDonald Islands", code: "HM", flagSrc: "assets/flags/territories/hm.svg" },
  { name: "Hong Kong", code: "HK", flagSrc: "assets/flags/territories/hk.svg" },
  { name: "Isle of Man", code: "IM", flagSrc: "assets/flags/territories/im.svg" },
  { name: "Jersey", code: "JE", flagSrc: "assets/flags/territories/je.svg" },
  { name: "Macau", code: "MO", flagSrc: "assets/flags/territories/mo.svg" },
  { name: "Martinique", code: "MQ", flagSrc: "assets/flags/territories/mq.svg" },
  { name: "Mayotte", code: "YT", flagSrc: "assets/flags/territories/yt.svg" },
  { name: "Montserrat", code: "MS", flagSrc: "assets/flags/territories/ms.svg" },
  { name: "New Caledonia", code: "NC", flagSrc: "assets/flags/territories/nc.svg" },
  { name: "Niue", code: "NU", flagSrc: "assets/flags/territories/nu.svg" },
  { name: "Norfolk Island", code: "NF", flagSrc: "assets/flags/territories/nf.svg" },
  { name: "Northern Mariana Islands", code: "MP", flagSrc: "assets/flags/territories/mp.svg" },
  { name: "Pitcairn Islands", code: "PN", flagSrc: "assets/flags/territories/pn.svg" },
  { name: "Puerto Rico", code: "PR", flagSrc: "assets/flags/territories/pr.svg" },
  { name: "Réunion", code: "RE", flagSrc: "assets/flags/territories/re.svg" },
  { name: "Saba", code: "BQ-SA", flagSrc: "assets/flags/territories/bq-sa.svg" },
  { name: "Saint Barthélemy", code: "BL", flagSrc: "assets/flags/territories/bl.svg" },
  { name: "Saint Helena", code: "SH", flagSrc: "assets/flags/territories/sh.svg" },
  { name: "Saint Martin", code: "MF", flagSrc: "assets/flags/territories/mf.svg" },
  { name: "Saint Pierre and Miquelon", code: "PM", flagSrc: "assets/flags/territories/pm.svg" },
  { name: "Sint Eustatius", code: "BQ-SE", flagSrc: "assets/flags/territories/bq-se.svg" },
  { name: "Sint Maarten", code: "SX", flagSrc: "assets/flags/territories/sx.svg" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", flagSrc: "assets/flags/territories/gs.svg" },
  { name: "Svalbard and Jan Mayen", code: "SJ", flagSrc: "assets/flags/territories/sj.svg" },
  { name: "Tokelau", code: "TK", flagSrc: "assets/flags/territories/tk.svg" },
  { name: "Tristan da Cunha", code: "TA", flagSrc: "assets/flags/territories/ta.svg" },
  { name: "Turks and Caicos Islands", code: "TC", flagSrc: "assets/flags/territories/tc.svg" },
  { name: "U.S. Minor Outlying Islands", code: "UM", flagSrc: "assets/flags/territories/um.svg" },
  { name: "U.S. Virgin Islands", code: "VI", flagSrc: "assets/flags/territories/vi.svg" },
  { name: "Wallis and Futuna", code: "WF", flagSrc: "assets/flags/territories/wf.svg" },
  { name: "Western Sahara", code: "EH", flagSrc: "assets/flags/territories/eh.svg" },
];
